name: Deploy-wiki

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.1.3
            - run: yarn global add vercel
            - run: vercel --token "$VERCEL_TOKEN" deploy --prod
              env:
                  VERCEL_TOKEN: ${{ secrets.vercelToken }}
